name = "npm-registry"
main = "src/index.ts"
compatibility_date = "2026-01-07"

compatibility_flags = [ "nodejs_compat" ]

[vars]
FALLBACK_REGISTRY_ENDPOINT = "https://registry.npmjs.org"

# Custom Domain
routes = [
  { pattern = "npm.figentra.com", custom_domain = true }
]

# KV Namespace (Terraform managed)
[[kv_namespaces]]
binding = "NPM_REGISTRY"
id = "58b31c317a9c4eb289277f289df94715"
preview_id = "2fa8389b7636437db99eea0ac68ff49b"

# R2 Bucket
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "npm-registry-packages"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "npm-registry-db"
database_id = "e17855a6-3a88-47a7-aa95-22e902fb4171"
# Migrations directory (relative to wrangler.toml)
migrations_dir = "database/migrations"
